### PR TITLE
Google auth ios

### PR DESCRIPTION
**Pull request by Nankun-Xu**
## Describe your changes
I add Google authenticator with Google OAuth,  it works on iOS

## Issue ticket number and link
#29 

## Screenshots / Video

https://github.com/Firm-Collective/ai-journal/assets/113734143/47e28836-d5e4-45cb-befc-81b5aaf2cc43

## Checklist
- [x] I have performed a self-review of my code
- [x] I have used `npx expo-doctor` to review any dependency issues.
- [ ] I have pulled and merged any recent changes from the main branch (no merge conflicts)
- [ ] I have tested thoroughly any edge cases that might break the application
- [x] I have deleted any console.log statements and useless comments

### CODE REVIEW

**Comment by dave-cao** [comment]
Tried out your branch. The google popup comes out but when I click my account name, nothing happens.
image

I see this in the logs after I press.
image

**Comment by Nankun-Xu** [comment]
> Tried out your branch. The google popup comes out but when I click my account name, nothing happens. image
> 
> I see this in the logs after I press. image

Did you run `npx expo prebuild`? Since I add a new library

**Comment by Lyton505** [comment]
how about we merge your changes and my changes into a feature/auth branch? @dave-cao and @Nankun-Xu that makes sense right?

**Comment by Nankun-Xu** [comment]
> how about we merge your changes and my changes into a feature/auth branch? @dave-cao and @Nankun-Xu that makes sense right?
Sure, sounds good to me!

**Comment by Lyton505** [comment]
I've added the branch [feat_auth](https://github.com/Firm-Collective/ai-journal/tree/feat_auth). It's up to date with main, so merge your changes there and close the pull request. I'm also merging mine.

**Comment by Nankun-Xu** [comment]
> I've added the branch [feat_auth](https://github.com/Firm-Collective/ai-journal/tree/feat_auth). It's up to date with main, so merge your changes there and close the pull request. I'm also merging mine.

Did you delete this branch? I couldn't reach it

**Comment by Lyton505** [comment]
Yes, use the other one feat_authExt

**Comment by Nankun-Xu** [comment]
I've already merged this branch into feat_authExt and will close this pr

**Pull request closed without merging**
